--- 
title: "STAT0002 Introduction to Probability and Statistics"
author: "Dr Paul Northrop"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
classoption: openany, a4paper
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
description: "Produces STAT0002 notes in an accessible format"
lang: "en-gb"
fontsize: 11pt
---

# The purpose of these notes {-}

These notes supplement the teaching materials available from the [STAT0002 Moodle page](https://moodle.ucl.ac.uk/course/view.php?id=8579).  The teaching events in STAT0002 will follow the general order of the topics covered in these notes.

Please see the [Overview](https://moodle.ucl.ac.uk/course/view.php?id=8579&section=1) section of the [STAT0002 Moodle page](https://moodle.ucl.ac.uk/course/view.php?id=8579) for important general information about STAT0002. 

```{r include=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown'
), 'packages.bib')
```

```{r kntir_auto_pdf, echo = FALSE, warning = FALSE, message = FALSE}
options(knit.graphics.auto_pdf = TRUE)
```

```{r, figsetup, include=FALSE}
knitr::opts_chunk$set(
  fig.align = 'center',
  out.width = '75%'
)
```
